** Check if a string is Pangrammatic Lipogram
- To understand what a pangrammatic lipogram is we will break this term down into 2 terms i.e. a pangram and a lipogram

- Pangram: A pangram or holoalphabetic sentence is a sentence using every letter
  of a given alphabet at least once. The best-known English pangram is “The
  quick brown fox jumps over the lazy dog.”

- Lipogram: A lipogram is a kind of constrained writing or word game consisting
  of writing paragraphs or longer works in which a particular letter or group of
  letters is avoided—usually a common vowel, and frequently E, the most common
  letter in the English language.

- Pangrammatic Lipogram: A pangrammatic lipogram is a text that uses every
  letter of the alphabet except one. For example, “The quick brown fox jumped
  over the lazy dog” omits the letter S, which the usual pangram includes by
  using the word jumps.

#+BEGIN_SRC

Original:
Mary had a little lamb
Its fleece was white as snow
And everywhere that Mary went
The lamb was sure to go

He followed her to school one day
That was against the rule
It made the children laugh and play
To see the lamb in school

Lipogram (Without "S"):
Mary had a little lamb
With fleece a pale white hue
And everywhere that Mary went
The lamb kept her in view

To academe he went with her,
Illegal, and quite rare;
It made the children laugh and play
To view the lamb in there

 #+END_SRC
